name: Go Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ryanjarv/xcgo:master@sha256:4db5d37a4762e6a074eb2f85c7267d521ddd9857b69467feaa56465f8375742a
      volumes:
        - ${{ github.workspace }}:/${{ github.workspace }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: 1.18.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: dist/*
